name: Audit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.2
      - name: Verify dependencies
        run: cd social && go mod verify
      - name: Build
        run: cd social && go build -v ./...
      - name: Run go vet
        run: cd social && go vet ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: cd social && staticcheck ./...
      - name: Run tests
        run: cd social && go test -race ./...
